proxy_cache_path /tmp/cache/release levels=1:2 keys_zone=release_cache:10m max_size=100m inactive=1m use_temp_path=off;
proxy_cache_path /tmp/cache/infra   levels=1:2 keys_zone=infra_cache:10m   max_size=100m inactive=2m use_temp_path=off;

server {
    listen 80;

    # métricas — sem cache
    location /release/metrics {
        proxy_pass http://release-service:8000/metrics;
        add_header X-Service release-service;
    }

    location /infra/metrics {
        proxy_pass http://infra-service:8080/metrics;
        add_header X-Service infra-service;
    }

    # release-service → cache de 10 segundos
    location /release/ {
        proxy_pass http://release-service:8000/;
        proxy_cache release_cache;
        proxy_cache_valid 200 10s;
        proxy_cache_use_stale error timeout updating;
        add_header X-Cache-Status $upstream_cache_status;
        add_header X-Service release-service;
    }

    # infra-service → cache de 60 segundos
    location /infra/ {
        proxy_pass http://infra-service:8080/;
        proxy_cache infra_cache;
        proxy_cache_valid 200 60s;
        proxy_cache_use_stale error timeout updating;
        add_header X-Cache-Status $upstream_cache_status;
        add_header X-Service infra-service;
    }
}